import type {
  Player,
  TeamStats,
  PredictionResult,
  NanoClawResponse,
} from "./index";

// ─── Players ──────────────────────────────────────────────────────────────────
export const MOCK_PLAYERS: Player[] = [
  {
    id: "p001",
    name: "Caleb Williams",
    position: "QB",
    college: "USC",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 1,
    draft_team: "CHI",
    ht_inches: 74,
    wt: 214,
    forty: 4.65,
    bench: 18,
    vertical: 33.5,
    broad_jump: 114,
    cone: 6.92,
    shuttle: 4.32,
  },
  {
    id: "p002",
    name: "Jayden Daniels",
    position: "QB",
    college: "LSU",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 2,
    draft_team: "WAS",
    ht_inches: 75,
    wt: 210,
    forty: 4.45,
    bench: 14,
    vertical: 35.0,
    broad_jump: 120,
    cone: 6.78,
    shuttle: 4.21,
  },
  {
    id: "p003",
    name: "Marvin Harrison Jr.",
    position: "WR",
    college: "Ohio State",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 4,
    draft_team: "ARI",
    ht_inches: 76,
    wt: 209,
    forty: 4.42,
    bench: 12,
    vertical: 38.5,
    broad_jump: 126,
    cone: 6.65,
    shuttle: 4.15,
  },
  {
    id: "p004",
    name: "Rome Odunze",
    position: "WR",
    college: "Washington",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 9,
    draft_team: "CHI",
    ht_inches: 75,
    wt: 212,
    forty: 4.45,
    bench: 11,
    vertical: 37.0,
    broad_jump: 123,
    cone: 6.72,
    shuttle: 4.22,
  },
  {
    id: "p005",
    name: "Joe Alt",
    position: "OT",
    college: "Notre Dame",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 5,
    draft_team: "LAC",
    ht_inches: 80,
    wt: 324,
    forty: 5.12,
    bench: 27,
    vertical: 28.0,
    broad_jump: 102,
    cone: 7.45,
    shuttle: 4.78,
  },
  {
    id: "p006",
    name: "Dallas Turner",
    position: "EDGE",
    college: "Alabama",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 17,
    draft_team: "MIN",
    ht_inches: 76,
    wt: 243,
    forty: 4.55,
    bench: 22,
    vertical: 36.5,
    broad_jump: 122,
    cone: 6.89,
    shuttle: 4.28,
  },
  {
    id: "p007",
    name: "Brock Bowers",
    position: "TE",
    college: "Georgia",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 13,
    draft_team: "LVR",
    ht_inches: 76,
    wt: 240,
    forty: 4.55,
    bench: 18,
    vertical: 35.0,
    broad_jump: 118,
    cone: 6.99,
    shuttle: 4.35,
  },
  {
    id: "p008",
    name: "Quinyon Mitchell",
    position: "CB",
    college: "Toledo",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 22,
    draft_team: "PHI",
    ht_inches: 71,
    wt: 192,
    forty: 4.33,
    bench: 14,
    vertical: 40.0,
    broad_jump: 131,
    cone: 6.55,
    shuttle: 4.05,
  },
  {
    id: "p009",
    name: "Laiatu Latu",
    position: "EDGE",
    college: "UCLA",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 15,
    draft_team: "IND",
    ht_inches: 77,
    wt: 259,
    forty: 4.67,
    bench: 24,
    vertical: 32.0,
    broad_jump: 110,
    cone: 7.08,
    shuttle: 4.52,
  },
  {
    id: "p010",
    name: "Terrion Arnold",
    position: "CB",
    college: "Alabama",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 24,
    draft_team: "DET",
    ht_inches: 72,
    wt: 202,
    forty: 4.38,
    bench: 16,
    vertical: 38.5,
    broad_jump: 128,
    cone: 6.6,
    shuttle: 4.1,
  },
  {
    id: "p011",
    name: "Drake Maye",
    position: "QB",
    college: "North Carolina",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 3,
    draft_team: "NE",
    ht_inches: 77,
    wt: 223,
    forty: 4.51,
    bench: 17,
    vertical: 34.0,
    broad_jump: 116,
    cone: 6.85,
    shuttle: 4.28,
  },
  {
    id: "p012",
    name: "Taliese Fuaga",
    position: "OT",
    college: "Oregon State",
    draft_year: 2024,
    draft_round: 1,
    draft_pick: 12,
    draft_team: "NO",
    ht_inches: 78,
    wt: 315,
    forty: 5.18,
    bench: 29,
    vertical: 27.0,
    broad_jump: 100,
    cone: 7.55,
    shuttle: 4.88,
  },
];

// ─── Team Stats ───────────────────────────────────────────────────────────────
export const MOCK_TEAM_STATS: TeamStats[] = [
  {
    team: "KC",
    year: 2023,
    wins: 11,
    losses: 6,
    points_for: 371,
    points_against: 290,
    offense_yards: 5892,
    defense_yards: 5210,
  },
  {
    team: "SF",
    year: 2023,
    wins: 12,
    losses: 5,
    points_for: 491,
    points_against: 298,
    offense_yards: 6495,
    defense_yards: 4980,
  },
  {
    team: "BAL",
    year: 2023,
    wins: 13,
    losses: 4,
    points_for: 483,
    points_against: 270,
    offense_yards: 6238,
    defense_yards: 5100,
  },
  {
    team: "BUF",
    year: 2023,
    wins: 11,
    losses: 6,
    points_for: 451,
    points_against: 311,
    offense_yards: 6102,
    defense_yards: 5340,
  },
  {
    team: "DAL",
    year: 2023,
    wins: 12,
    losses: 5,
    points_for: 509,
    points_against: 287,
    offense_yards: 6614,
    defense_yards: 4870,
  },
  {
    team: "DET",
    year: 2023,
    wins: 12,
    losses: 5,
    points_for: 461,
    points_against: 395,
    offense_yards: 6756,
    defense_yards: 5780,
  },
  {
    team: "MIA",
    year: 2023,
    wins: 11,
    losses: 6,
    points_for: 496,
    points_against: 391,
    offense_yards: 6648,
    defense_yards: 5910,
  },
  {
    team: "PHI",
    year: 2023,
    wins: 11,
    losses: 6,
    points_for: 420,
    points_against: 329,
    offense_yards: 6210,
    defense_yards: 5120,
  },
];

// ─── Prediction Results ───────────────────────────────────────────────────────
export const MOCK_PREDICTIONS: Record<string, PredictionResult> = {
  player_projection: {
    model: "player_projection",
    score: 87.4,
    confidence: 0.82,
    shap_values: {
      forty: 0.31,
      vertical: 0.22,
      wt: 0.18,
      college_tier: 0.15,
      bench: 0.08,
      cone: 0.06,
    },
  },
  draft_optimizer: {
    model: "draft_optimizer",
    score: 92.1,
    confidence: 0.88,
    shap_values: {
      position_scarcity: 0.38,
      forty: 0.24,
      college_tier: 0.2,
      vertical: 0.12,
      wt: 0.06,
    },
  },
  health_analyzer: {
    model: "health_analyzer",
    score: 74.6,
    confidence: 0.71,
    shap_values: {
      wt: 0.34,
      bench: 0.28,
      forty: 0.2,
      broad_jump: 0.12,
      shuttle: 0.06,
    },
  },
  team_diagnosis: {
    model: "team_diagnosis",
    score: 68.3,
    confidence: 0.74,
    shap_values: {
      offense_yards: 0.35,
      points_for: 0.28,
      defense_yards: 0.22,
      points_against: 0.15,
    },
  },
  roster_fit: {
    model: "roster_fit",
    score: 79.2,
    confidence: 0.77,
    shap_values: {
      position_need: 0.4,
      forty: 0.22,
      wt: 0.18,
      college_tier: 0.12,
      vertical: 0.08,
    },
  },
  positional_flexibility: {
    model: "positional_flexibility",
    score: 65.8,
    confidence: 0.68,
    shap_values: {
      cone: 0.33,
      shuttle: 0.28,
      forty: 0.22,
      vertical: 0.17,
    },
  },
};

// ─── NanoClaw canned responses ────────────────────────────────────────────────
export const MOCK_NULLCLAW_RESPONSES: NanoClawResponse[] = [
  {
    reply:
      "Based on combine metrics, Caleb Williams ranks as the top QB prospect. His 4.65 forty and elite arm talent translate well to the next level. The Player Projection model gives him an 87.4 score with 82% confidence.",
    tool_calls: [
      {
        model: "player_projection",
        result: MOCK_PREDICTIONS.player_projection,
      },
    ],
  },
  {
    reply:
      "Looking at the WR class, Marvin Harrison Jr. stands out with a 4.42 forty and 38.5-inch vertical. The Draft Optimizer scores him at 92.1 — highest in this class — driven largely by positional scarcity at elite WR.",
    tool_calls: [
      { model: "draft_optimizer", result: MOCK_PREDICTIONS.draft_optimizer },
    ],
  },
  {
    reply:
      "The Health Analyzer flags linemen over 320 lbs as moderate risk by Year 3. Joe Alt (324 lbs) scores 74.6 — solid but worth monitoring. Bench press (27 reps) is a positive indicator for durability.",
    tool_calls: [
      { model: "health_analyzer", result: MOCK_PREDICTIONS.health_analyzer },
    ],
  },
];

// ─── SQL Query mock results ───────────────────────────────────────────────────
export const MOCK_QUERY_RESULTS: Record<string, unknown>[] = [
  {
    name: "Caleb Williams",
    position: "QB",
    college: "USC",
    forty: 4.65,
    wt: 214,
    draft_round: 1,
  },
  {
    name: "Jayden Daniels",
    position: "QB",
    college: "LSU",
    forty: 4.45,
    wt: 210,
    draft_round: 1,
  },
  {
    name: "Marvin Harrison Jr.",
    position: "WR",
    college: "Ohio State",
    forty: 4.42,
    wt: 209,
    draft_round: 1,
  },
  {
    name: "Quinyon Mitchell",
    position: "CB",
    college: "Toledo",
    forty: 4.33,
    wt: 192,
    draft_round: 1,
  },
  {
    name: "Terrion Arnold",
    position: "CB",
    college: "Alabama",
    forty: 4.38,
    wt: 202,
    draft_round: 1,
  },
  {
    name: "Brock Bowers",
    position: "TE",
    college: "Georgia",
    forty: 4.55,
    wt: 240,
    draft_round: 1,
  },
  {
    name: "Dallas Turner",
    position: "EDGE",
    college: "Alabama",
    forty: 4.55,
    wt: 243,
    draft_round: 1,
  },
  {
    name: "Laiatu Latu",
    position: "EDGE",
    college: "UCLA",
    forty: 4.67,
    wt: 259,
    draft_round: 1,
  },
];
